import localFont from "next/font/local";
import "./globals.css";
import Announcement from "./_components/_atoms/Announcement";
import ContactLine from "./_components/ContactLine";
import Header from "./_components/Header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div><Announcement/></div>
        <div className='hidden min-[950px]:block'><ContactLine/></div>
        <div><Header/></div>
        {children}
      </body>
    </html>
  );
}
